### ISSUE TITLE
SshPuzzles.java: Handle SshPuzzles errors outp... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-todos#40]
The puzzle ``12-0273df37`` originating from #12 has to be resolved:

https://github.com/self-xdsd/self-todos/blob/09c70978a11fac263f458ebe74320b2fe62ed2e7/src/main/java/com/selfxdsd/todos/SshPuzzles.java#L48-L53

"Handle SshPuzzles errors output with PuzzlesProcessingException. Right now there is one single String output. Instead of a String we should have 2 streams one for puzzles and one for errors. The puzzle InputStream will processed by DocumentPuzzles and the error stream will be collected into a error message and thrown as PuzzlesProcessingException in SshPuzzles.".

It was created by cristianpela on 2020-09-07T16:34:12Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-06T18:48:13.635313``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@fellahi-ali I don't think there is anything to do here. We already catch any exceptions and we post a comment on the Commit if there are any problems.

**Comment by charlesmike** [comment]
@fellahi-ali Don't forget to close this ticket before the deadline (2021-01-06T18:48:13). You are past the first half of the allowed period.

**Comment by fellahi-ali** [comment]
> @fellahi-ali I don't think there is anything to do here. We already catch any exceptions and we post a comment on the Commit if there are any problems.

@amihaiemil I think what @criske meant by this issue is that the error outputs of the ssh.exec() is not handled/reported correctly as it's directed to the same `baos` as the standard output, and this method only rethrow `IOException`s but doesn't handle the case where the `ssh.exec()` returns with non-zero error code.      
https://github.com/self-xdsd/self-todos/blob/cf1f7ece42fa0027094ca4952dc13e4a7036f0de/src/main/java/com/selfxdsd/todos/SshPuzzles.java#L126-L130

**Comment by amihaiemil** [comment]
@fellahi-ali Yes, now that you mention it, I think that too. But on the other hand, we will catch that problem when trying to parse the result, right?

So we are not handling the non-zero return code or other errors directly, but we will catch the problem anyway at parsing.  I think this is enough? 

@criske do you think we need anything else? :D

**Comment by fellahi-ali** [comment]
> @fellahi-ali Yes, now that you mention it, I think that too. But on the other hand, we will catch that problem when trying to parse the result, right?

Sure, but my concern is that the `SshPuzzles.exec()` is used twice in the `process()` method and if one of them fail because the non-zero exit code of the ssh command (without throwing the `IOException`) our code will not fail until `this.next.process(puzzles);` will fail in `JsonPuzzles` or any other implementation far away from the original error which could be difficult to debug! or I'm missing something?
https://github.com/self-xdsd/self-todos/blob/cf1f7ece42fa0027094ca4952dc13e4a7036f0de/src/main/java/com/selfxdsd/todos/SshPuzzles.java#L86-L110

**Comment by amihaiemil** [comment]
@fellahi-ali you are right, that might be a problem... not a big problem, but a problem nevertheless. 

So if you wish have a look on the API from jcabi-ssh, how we could do this separate stream thing.
I think you already spent 30min here, so it's ok if you continue for another hour and a half, I'll pay 2h for this ticket :D

**Comment by fellahi-ali** [comment]
> I think you already spent 30min here, so it's ok if you continue for another hour and a half. I'll pay 2h for this ticket :D

Thanks @amihaiemil for your kindness :)
Ironically, I have already spent more than 3 hours trying to understand self-todos code & jcabi-ssh API, but honestly I didn't bother myself with how much I will be paid because I'm really learning new things and this is my first task in this project so 2h is more than fair. 

> So if you wish have a look on the API from jcabi-ssh, how we could do this separate stream thing.

Fortunately, I think I have already figured that out while trying to understand how things are wired, so I need just try to implement the solution :)

**Comment by criske** [comment]
@fellahi-ali yeah, the idea this issue was treat to `Shell`'s `stdout` and `stderr`  separately. Basically catch `stderr` at the get go in `SshPuzzles` and leave the next `Puzzles` to process the `stdout` as a string, as we're doing right now. 
From there, in the future if memory will be problem or the whole process is too slow, we might convert  `stdout`  to an `Inputsteam` using piping, but I doubt we'll ever need to that :D
@amihaiemil btw, couldn't we just move the second exec command to `cloneRepoAndPdd.sh`?

**Comment by amihaiemil** [comment]
@criske 

> btw, couldn't we just move the second exec command to cloneRepoAndPdd.sh?

I remember I wanted to do this and it wasn't possible for some reason (but I don't remember why haha).
Let's try to do it later, in a new ticket :D

**Comment by fellahi-ali** [comment]
@amihaiemil @criske I can't understand how the todo-finder-cli is run? as the  current `cloneRepoAndPdd.sh` still run `pdd` command.

**Comment by amihaiemil** [comment]
@fellahi-ali sorry for the confusion.

On the Test and Prod servers, ``pdd`` is the alias for ``java -jar /path/to/todo-finder-cli``.

So running ``pdd`` will execute that java command.

**Comment by amihaiemil** [comment]
paid with transaction id 41Y44427J6727910W

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
